Create table VENUS_ROLE (
   ROLE_ID serial,
   ROLE_NAME VARCHAR(50) NOT NULL,
   CREATE_DATE DATE NOT NULL,
   LAST_MODIFIED_USER_ID VARCHAR(50) NOT NULL,
   LAST_MODIFIED_DATE DATE NOT NULL,
   UNIQUE (ROLE_NAME),
   PRIMARY KEY (ROLE_ID)
);
   
Create table VENUS_USER (
   USER_ID serial,
   USER_NAME VARCHAR(20) NOT NULL,
   FULL_NAME VARCHAR(50) NOT NULL,
   EMAIL VARCHAR(50) NOT NULL,
   SEX INT NOT NULL,
   ADDRESS VARCHAR(200) NOT NULL,
   PHONE_NUMBER VARCHAR(11) NOT NULL,
   AVATAR_PATH VARCHAR(200) NOT NULL,
   PASSWORD VARCHAR(32) NOT NULL,
   PASSWORD_EXPIRED_DATE DATE NOT NULL,
   LAST_LOGIN_DATE DATE,
   NUMBER_TRY_LOGIN INT,
   IS_ACTIVED INT,
   IS_LOCKED INT,
   IS_DELETED INT,
   CREATE_USER_ID VARCHAR(50) NOT NULL,
   CREATE_DATE DATE NOT NULL,
   LAST_MODIFIED_USER_ID VARCHAR(50) NOT NULL,
   LAST_MODIFIED_DATE DATE NOT NULL,
   UNIQUE(EMAIL),
   PRIMARY KEY (USER_ID)
);

CREATE TABLE VENUS_USER_ROLE (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_VENUS_USER FOREIGN KEY (USER_ID) REFERENCES VENUS_USER (USER_ID),
    CONSTRAINT FK_VENUS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES VENUS_ROLE (ROLE_ID)
);
